# Generated by Django 4.1.3 on 2023-07-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.URLField(default='https://jphxdckjtcxleelhjfhy.supabase.co/storage/v1/object/public/images/default.png'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='picture',
            field=models.URLField(default='https://jphxdckjtcxleelhjfhy.supabase.co/storage/v1/object/public/images/default.png'),
        ),
    ]
