# Generated by Django 4.1.3 on 2023-11-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityincart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='soldcommodity',
            name='commodity_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
