# Generated by Django 4.1.3 on 2023-11-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_commodityincart_quantity_soldcommodity_commodity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodityincart',
            name='quantity',
        ),
    ]
