# Generated by Django 4.1.3 on 2023-11-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_commodityincart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldcommodity',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
